const mongoose=require("mongoose");

const TreatmentSchema=mongoose.Schema({
    refNo:{
        type:Number,
        required:true,
        trim:true
    },
    name:{
        type:String,
        required:true,
        trim:true 
    },
    address:{
        type:String,
        required:true,
        trim:true,
    },
    thir:{
        type:String,
        required:true,
        trim:true,
    },
    app:{
        type:String,
        required:true,
        trim:true,
    },
    gender:{
        type:String,
        required:true,
        trim:true
    },
    religion:{
        type:String,
        required:true,
        trim:true
    },
    age:{
        type:Number,
        required:true,
        trim:true,
    },
    height:{
        type:Number,
        required:true,
        trim:true,
    },
    mind:{
        type:String,
        required:true,
        trim:true,
    },
    date:{
        type:Date,
        required:true,
        trim:true,
    },
    desire:{
        type:String,
        required:true,
        trim:true,
    },
    weight:{
        type:Number,
        required:true,
        trim:true,
    },
    adct:{
        type:String,
        required:true,
        trim:true,
    },
    swt:{
        type:String,
        required:true,
        trim:true,
    },
    tng:{
        type:String,
        required:true,
        trim:true,
    },
    nGl:{
        type:String,
        required:true,
        trim:true,
    },
    bp:{
        type:String,
        required:true,
        trim:true,
    },
    prt:{
        type:String,
        required:true,
        trim:true,
    },
    hc:{
        type:String,
        required:true,
        trim:true,
    },
    chest:{
        type:String,
        required:true,
        trim:true
    },
    ph:{
        type:String,
        required:true,
        trim:true,
    },
    fh:{
        type:String,
        required:true,
        trim:true,
    },
    complain:{
        type:String,
        required:true,
        trim:true,
    },
    prescriptionDate:{
        type:Date,
        required:true,
        trim:true,
    },
    followUp:{
        type:String,
        required:true,
        trim:true,
    },
    rx:{
        type:String,
        required:true,
        trim:true,
    },
    medicineCourse:{
        type:String,
        required:true,
        trim:true,
    },
    days:{
        type:Number,
        required:true,
        trim:true,
    }
})
module.exports=mongoose.model("Treatment",TreatmentSchema)